/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Proyecto;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alvaro
 */
public class VentanaPacientes extends javax.swing.JPanel {

    /**
     * Creates new form VentanaPacientes
     */
    public VentanaPacientes() {
        initComponents();
        mostrarDatos();
    }

    public void mostrarDatos() {
        try {
            ConexionBD conect = new ConexionBD();
            conect.conexion();

            String[] titulos = {"DNI", "Nombre", "Apellidos", "Edad", "Sexo"};

            String[] registros = new String[5];

            DefaultTableModel modelo = new DefaultTableModel(null, titulos);

            String sql = "SELECT * FROM pacientes";

            try {
                Statement st = conect.conect.createStatement();
                ResultSet rs = st.executeQuery(sql);

                while (rs.next()) {
                    registros[0] = rs.getString("dni");
                    registros[1] = rs.getString("nombre");
                    registros[2] = rs.getString("apellidos");
                    registros[3] = rs.getString("edad");
                    registros[4] = rs.getString("sexo");

                    modelo.addRow(registros);
                }
                tablaPacientes.setModel(modelo);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR AL MOSTRAR DATOS");
            }
            conect.conect.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void eliminarDatos() {
        try {
            ConexionBD conect = new ConexionBD();
            conect.conexion();

            int filaSeleccionada = tablaPacientes.getSelectedRow();

            String sql = "DELETE FROM pacientes WHERE dni = '" + tablaPacientes.getValueAt(filaSeleccionada, 0) + "'";

            Statement st = conect.conect.createStatement();
            int n = st.executeUpdate(sql);

            if (n >= 0) {
                JOptionPane.showMessageDialog(null, "PACIENTE ELIMINADO.");
            }
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPacientes = new javax.swing.JTable();
        nombreBuscar = new javax.swing.JLabel();
        nombreBuscarBox = new javax.swing.JTextField();
        sexoBuscar = new javax.swing.JLabel();
        sexoBuscarBox = new javax.swing.JComboBox<>();
        botonBuscar = new javax.swing.JButton();
        botonBuscar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        tablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaPacientes);

        nombreBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombreBuscar.setForeground(new java.awt.Color(0, 0, 0));
        nombreBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreBuscar.setText("Nombre del Paciente");

        nombreBuscarBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreBuscarBox.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));

        sexoBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sexoBuscar.setForeground(new java.awt.Color(0, 0, 0));
        sexoBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sexoBuscar.setText("Sexo");

        sexoBuscarBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Sexo...", "Hombre", "Mujer" }));
        sexoBuscarBox.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));

        botonBuscar.setBackground(new java.awt.Color(0, 153, 153));
        botonBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscar.setText("Buscar");
        botonBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonBuscar1.setBackground(new java.awt.Color(0, 153, 153));
        botonBuscar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscar1.setText("Actualizar Lista");
        botonBuscar1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        botonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreBuscarBox, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexoBuscarBox, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(248, 248, 248)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(517, 517, 517)
                .addComponent(botonBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sexoBuscar)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(nombreBuscarBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexoBuscarBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        try {
            ConexionBD conect = new ConexionBD();
            conect.conexion();

            String nombre = nombreBuscarBox.getText();
            String sexo = sexoBuscarBox.getSelectedItem().toString();

            PreparedStatement ps;
            String sql;

            if (nombre.equals("")) {
                nombre = null;
            }
            if (sexo.equals("Seleccione Sexo...")) {
                sexo = null;
            }

            if (nombre != null && sexo == null) {
                sql = "SELECT * FROM pacientes WHERE (nombre LIKE ?)";
                ps = conect.conect.prepareStatement(sql);

                ps.setString(1, nombre);

                ps.executeUpdate();
            }
            if (nombre == null && sexo != null) {
                sql = "SELECT * FROM pacientes WHERE (sexo = ?)";
                ps = conect.conect.prepareStatement(sql);

                ps.setString(1, sexo);

                ps.executeUpdate();
            }
            if (nombre != null && sexo != null) {
                sql = "SELECT * FROM pacientes WHERE (nombre LIKE ?) AND (sexo = ?)";
                ps = conect.conect.prepareStatement(sql);

                ps.setString(1, nombre);
                ps.setString(2, sexo);

                ps.executeUpdate();
            }
            conect.conect.close();
        } catch (SQLException e) {
        }

    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonBuscar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreBuscar;
    private javax.swing.JTextField nombreBuscarBox;
    private javax.swing.JLabel sexoBuscar;
    private javax.swing.JComboBox<String> sexoBuscarBox;
    private javax.swing.JTable tablaPacientes;
    // End of variables declaration//GEN-END:variables
}
